Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -36,11 +36,11 @@ jobs:
           name: coverage-report
           path: "**/coverage.opencover.xml"
           
-      # ✅ FORZAR QUE GITHUB DETECTE EL STATUS CHECK
+      # ✅ SOLUCIÓN: Reportar un Status Check con Environment File
       - name: Set Job Status
         if: success()
-        run: echo "::set-output name=status::success"
+        run: echo "status=success" >> $GITHUB_ENV
 
       - name: Fail Job if Tests Fail
         if: failure()
-        run: echo "::set-output name=status::failure" && exit 1
+        run: echo "status=failure" >> $GITHUB_ENV && exit 1
